Agenda/Models/Atividades.cs
using System;

namespace Agenda.Models
{
    public class Atividades
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public DateTime? DataInicio { get; set; }
        public DateTime? DataFim { get; set; }
        public string Status { get; set; }
    }
}

Agenda/Models/ErrorViewModel.cs
using System;

namespace Agenda.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Agenda/Controllers/AtividadesController.cs
using System;
using System.Diagnostics;
using System.Linq;
using Agenda.Business;
using Agenda.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Agenda.Controllers
{
    public class AtividadesController : Controller
    {
        AtividadeBusiness _atividadesBusiness = new AtividadeBusiness();

        public IActionResult Index()
        {
            var atividade = _atividadesBusiness.Obter().OrderBy(p => p.DataInicio);
            return View(atividade);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(IFormCollection collection)
        {
            Atividades atividade = new Atividades
            {
                Nome = collection["Nome"].ToString(),
                Descricao = collection["Descricao"].ToString(),
                DataInicio = string.IsNullOrEmpty(collection["DataInicio"]) ? (DateTime?)null : Convert.ToDateTime(collection["DataInicio"]),
                DataFim = string.IsNullOrEmpty(collection["DataFim"]) ? (DateTime?)null : Convert.ToDateTime(collection["DataFim"]),
            };
            _atividadesBusiness.Salvar(atividade);
            return View();
        }

        public ActionResult Edit(int id)
        {
            // TODO : Validadr se a atividade não tem a data de inicio menor que a de fim
            var atividade = _atividadesBusiness.Obter(id);
            if (atividade == null) return NotFound();
            _atividadesBusiness.Alterar(atividade);
            return View(atividade);
        }

        [HttpPost]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Atividades atividade = new Atividades
                {
                    Id = id,
                    Nome = collection["Nome"].ToString(),
                    Descricao = collection["Descricao"].ToString(),
                    DataInicio = string.IsNullOrEmpty(collection["DataInicio"]) ? (DateTime?)null : Convert.ToDateTime(collection["DataInicio"]),
                    DataFim = string.IsNullOrEmpty(collection["DataFim"]) ? (DateTime?)null : Convert.ToDateTime(collection["DataFim"]),
                };
                if (atividade == null) return NotFound();
                _atividadesBusiness.Alterar(atividade);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            var atividade = _atividadesBusiness.Obter(id);
            if (atividade == null) return NotFound();
            return View(atividade);
        }

        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            _atividadesBusiness.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // GET: Arquivo/Details/5
        public ActionResult Details(int id)
        {
            var atividade = _atividadesBusiness.Obter(id);
            if (atividade == null) return NotFound();
            return View(atividade);
        }
    }
}

Agenda/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Agenda.Models;

namespace Agenda.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Agenda/Views/Atividades/Create.cshtml
@model Agenda.Models.Atividades

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agenda/Views/Atividades/Delete.cshtml
@model Agenda.Models.Atividades

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Você realmente que deletar isso?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Agenda/Views/Atividades/Details.cshtml
@model Agenda.Models.Atividades
@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Atividade</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Agenda/Views/Atividades/Edit.cshtml
@model Agenda.Models.Atividades

@{
    ViewData["Title"] = "Editar";
}

<h1>Edit</h1>

<h4>AtividadeViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agenda/Views/Atividades/Index.cshtml
@model IEnumerable<Agenda.Models.Atividades>
@{
    ViewData["Title"] = "Index";
}
<p>
    <a asp-action="Create">Criar nova Atividade</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataFim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.Status == "Não Fazer")
            {
                <tr style="background-color:rgba(147, 153, 148, 0.51)">
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td style="margin-left:20px">
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataFim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                    </td>
                </tr>
            }
            @if (item.Status == "Concluída")
            {
                <tr style="background-color:rgba(53, 247, 92, 0.51)">
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td style="margin-left:20px">
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataFim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                    </td>
                </tr>
            }
            @if (item.Status == "Pra fazer")
            {
                <tr style="background-color:#FFFFFF">
                    <td >
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td style="margin-left:20px">
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataFim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                     <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                    </td>
                </tr>
            }
            @if (item.Status == "Pendente")
            {
                <tr style="background-color:rgba(53, 208, 247, 0.51)">
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td style="margin-left:20px">
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataFim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                     <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Agenda/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Agenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="atividades" asp-controller="Atividades" asp-action="Index">Agenda</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Agenda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>